# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTripSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_rex_key', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_label', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_rex_key', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_label', models.CharField(blank=True, max_length=100, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.CharField(blank=True, max_length=20, null=True)),
                ('is_one_way', models.BooleanField(default=False)),
                ('adult_count', models.IntegerField(default=0)),
                ('children_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('senior_count', models.IntegerField(default=0)),
                ('promo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('ticket_total', models.DecimalField(decimal_places=2, default=b'0.00', max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=b'0.00', max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=b'0.00', max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=b'0.00', max_digits=10)),
                ('reward_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'OPEN', b'Open'), (b'CLOSED', b'Closed')], default=b'OPEN', max_length=20)),
                ('sales_order_rex_key', models.CharField(blank=True, max_length=30, null=True)),
                ('pickled_rex_booking_session', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rex_key', models.CharField(blank=True, max_length=20, null=True)),
                ('traveler_class', models.CharField(choices=[(b'ADULT', b'Adult'), (b'CHILD', b'Child'), (b'STUDENT', b'Student'), (b'SENIOR', b'Senior')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=100)),
                ('ticket_total', models.DecimalField(decimal_places=2, default=b'0.00', max_digits=10)),
                ('bookTripSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_profiles', to='book_trip.BookTripSession')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_key', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_key', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_key', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_key', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_name', models.CharField(blank=True, max_length=100, null=True)),
                ('depart_date', models.DateField()),
                ('depart_time', models.CharField(blank=True, max_length=20, null=True)),
                ('arrive_date', models.DateField()),
                ('arrive_time', models.CharField(blank=True, max_length=20, null=True)),
                ('carrier_key', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('route_key', models.CharField(blank=True, max_length=100, null=True)),
                ('route_name', models.CharField(blank=True, max_length=100, null=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('rex_crs', models.CharField(blank=True, max_length=60, null=True)),
                ('allow_pick_seats', models.BooleanField()),
                ('alert_msg_img_url', models.CharField(blank=True, max_length=400, null=True)),
                ('bookTripSession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='book_trip.BookTripSession')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_legs', to='book_trip.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Traveller_Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(blank=True, max_length=10, null=True)),
                ('travelerProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_trip.TravelerProfile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='book_trip.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='seat_assignments',
            field=models.ManyToManyField(through='book_trip.Trip_Traveller_Seat', to='book_trip.Trip'),
        ),
        migrations.AddField(
            model_name='booktripsession',
            name='origin_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_trip_session', to='book_trip.Trip'),
        ),
        migrations.AddField(
            model_name='booktripsession',
            name='return_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_trip_session', to='book_trip.Trip'),
        ),
    ]
